def n_plus_1(n):
    result = n+1

n_plus_1(3)
print(result)

# 함수 내에서 사용한 변수는 밖에서 접근 불가하여 오류 발생